### ISSUE TITLE
Upload new layer fails

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/bioeco-geonode#135]
```
[pid: 75891|app: 0|req: 30/303] 193.191.134.2 () {86 vars in 1733 bytes} [Wed May  4 10:46:24 2022] GET /api/v2/uploads?filter{-state}=PROCESSED&page=1&page_size=99999 => generated 89 bytes in 31 msecs (HTTP/1.1 200) 9 headers in 358 bytes (1 switches on core 0)
Error creating import session
Traceback (most recent call last):
  File "./geonode/upload/upload.py", line 307, in save_step
    next_id = _get_next_id()
  File "./geonode/upload/upload.py", line 230, in _get_next_id
    importer_sessions = gs_uploader.get_sessions()
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 47, in get_sessions
    return self._call(self.client.get_imports)
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 34, in _call
    robj = fun(*args)
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 221, in get_imports
    return parse_response(self._request(self.url("imports")))
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 198, in _request
    raise RequestFailed(resp.status, content)
gsimporter.api.RequestFailed: (401, b'<!doctype html><html lang="en"><head><title>HTTP Status 401 \xe2\x80\x93 Unauthorized</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 \xe2\x80\x93 Unauthorized</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Unauthorized</p><p><b>Description</b> The request has not been applied because it lacks valid authentication credentials for the target resource.</p><hr class="line" /><h3>Apache Tomcat/9.0.53</h3></body></html>')
request failed
Traceback (most recent call last):
  File "./geonode/upload/views.py", line 739, in view
    resp = _steps[step](req, upload_session)
  File "./geonode/upload/views.py", line 203, in save_step_view
    import_session, upload = save_step(
  File "./geonode/upload/upload.py", line 410, in save_step
    raise e
  File "./geonode/upload/upload.py", line 307, in save_step
    next_id = _get_next_id()
  File "./geonode/upload/upload.py", line 230, in _get_next_id
    importer_sessions = gs_uploader.get_sessions()
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 47, in get_sessions
    return self._call(self.client.get_imports)
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 34, in _call
    robj = fun(*args)
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 221, in get_imports
    return parse_response(self._request(self.url("imports")))
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 198, in _request
    raise RequestFailed(resp.status, content)
gsimporter.api.RequestFailed: (401, b'<!doctype html><html lang="en"><head><title>HTTP Status 401 \xe2\x80\x93 Unauthorized</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 \xe2\x80\x93 Unauthorized</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Unauthorized</p><p><b>Description</b> The request has not been applied because it lacks valid authentication credentials for the target resource.</p><hr class="line" /><h3>Apache Tomcat/9.0.53</h3></body></html>')
Upload error response: (401, b'<!doctype html><html lang="en"><head><title>HTTP Status 401 \xe2\x80\x93 Unauthorized</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 \xe2\x80\x93 Unauthorized</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Unauthorized</p><p><b>Description</b> The request has not been applied because it lacks valid authentication credentials for the target resource.</p><hr class="line" /><h3>Apache Tomcat/9.0.53</h3></body></html>')
```

**Comment by pieterprovoost** [comment]
Appears to be fixed after a container rebuild.
