### ISSUE TITLE
New layer upload stuck at 66% 

### ISSUE THREAD

**Issue by SeritavdW** [iobis/bioeco-geonode#158]

**Comment by pieterprovoost** [comment]
Confirmed, looking into it.

```
nginx4geonode    | 178.119.97.51 - - [29/Jul/2022:08:24:08 +0000] "GET /layers/upload HTTP/1.1" 200 10391 "https://geonode.goosocean.org/layers/upload" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
db4geonode       | 2022-07-29 08:24:08.681 UTC [2988664] ERROR:  column layers_layer.in_obis does not exist at character 2228
db4geonode       | 2022-07-29 08:24:08.681 UTC [2988664] STATEMENT:  SELECT "base_resourcebase"."id", "base_resourcebase"."polymorphic_ctype_id", "base_resourcebase"."uuid", "base_resourcebase"."title", "base_resourcebase"."abstract", "base_resourcebase"."purpose", "base_resourcebase"."owner_id", "base_resourcebase"."alternate", "base_resourcebase"."date", "base_resourcebase"."date_type", "base_resourcebase"."edition", "base_resourcebase"."attribution", "base_resourcebase"."doi", "base_resourcebase"."maintenance_frequency", "base_resourcebase"."restriction_code_type_id", "base_resourcebase"."constraints_other", "base_resourcebase"."license_id", "base_resourcebase"."language", "base_resourcebase"."category_id", "base_resourcebase"."spatial_representation_type_id", "base_resourcebase"."temporal_extent_start", "base_resourcebase"."temporal_extent_end", "base_resourcebase"."supplemental_information", "base_resourcebase"."data_quality_statement", "base_resourcebase"."group_id", "base_resourcebase"."bbox_polygon"::bytea, "base_resourcebase"."ll_bbox_polygon"::bytea, "base_resourcebase"."srid", "base_resourcebase"."csw_typename", "base_resourcebase"."csw_schema", "base_resourcebase"."csw_mdsource", "base_resourcebase"."csw_insert_date", "base_resourcebase"."csw_type", "base_resourcebase"."csw_anytext", "base_resourcebase"."csw_wkt_geometry", "base_resourcebase"."metadata_uploaded", "base_resourcebase"."metadata_uploaded_preserve", "base_resourcebase"."metadata_xml", "base_resourcebase"."popular_count", "base_resourcebase"."share_count", "base_resourcebase"."featured", "base_resourcebase"."is_published", "base_resourcebase"."is_approved", "base_resourcebase"."thumbnail_url", "base_resourcebase"."detail_url", "base_resourcebase"."rating", "base_resourcebase"."created", "base_resourcebase"."last_updated", "base_resourcebase"."dirty_state", "base_resourcebase"."resource_type", "base_resourcebase"."metadata_only", "layers_layer"."resourcebase_ptr_id", "layers_layer"."title_en", "layers_layer"."abstract_en", "layers_layer"."purpose_en", "layers_layer"."constraints_other_en", "layers_layer"."supplemental_information_en", "layers_layer"."data_quality_statement_en", "layers_layer"."url", "layers_layer"."sops", "layers_layer"."outputs", "layers_layer"."obis_pub_interest", "layers_layer"."in_obis", "layers_layer"."funding", "layers_layer"."funding_sector", "layers_layer"."workspace", "layers_layer"."store", "layers_layer"."storeType", "layers_layer"."name", "layers_layer"."typename", "layers_layer"."is_mosaic", "layers_layer"."has_time", "layers_layer"."has_elevation", "layers_layer"."time_regex", "layers_layer"."elevation_regex", "layers_layer"."default_style_id", "layers_layer"."remote_service_id", "layers_layer"."charset", "layers_layer"."upload_session_id", "layers_layer"."use_featureinfo_custom_template", "layers_layer"."featureinfo_custom_template" FROM "layers_layer" INNER JOIN "base_resourcebase" ON ("layers_layer"."resourcebase_ptr_id" = "base_resourcebase"."id") WHERE "base_resourcebase"."uuid" = 'd132c0d0-0f17-11ed-bf13-0242ac140006'
celery4geonode   | column layers_layer.in_obis does not exist
celery4geonode   | LINE 1: ...r"."outputs", "layers_layer"."obis_pub_interest", "layers_la...
celery4geonode   |                                                              ^
celery4geonode   | Traceback (most recent call last):
celery4geonode   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
celery4geonode   |     return self.cursor.execute(sql, params)
celery4geonode   | psycopg2.errors.UndefinedColumn: column layers_layer.in_obis does not exist
celery4geonode   | LINE 1: ...r"."outputs", "layers_layer"."obis_pub_interest", "layers_la...
celery4geonode   |                                                              ^
celery4geonode   | 
celery4geonode   | 
celery4geonode   | The above exception was the direct cause of the following exception:
celery4geonode   | 
celery4geonode   | Traceback (most recent call last):
celery4geonode   |   File "/usr/src/geonode/geonode/upload/views.py", line 608, in final_step_view
celery4geonode   |     saved_layer = final_step(upload_session, upload_session.user, layer_id)
celery4geonode   |   File "/usr/src/geonode/geonode/upload/upload.py", line 747, in final_step
celery4geonode   |     saved_layer, created = Layer.objects.get_or_create(
celery4geonode   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
celery4geonode   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
celery4geonode   |   File "/usr/local/lib/python3.8/site-packages/modeltranslation/manager.py", line 398, in get_or_create
celery4geonode   |     return super(MultilingualQuerySet, self).get_or_create(*args, **kwargs)
celery4geonode   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 538, in get_or_create
celery4geonode   |     return self.get(**kwargs), False
celery4geonode   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 402, in get
celery4geonode   |     num = len(clone)
celery4geonode   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 256, in __len__
celery4geonode   |     self._fetch_all()
celery4geonode   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
celery4geonode   |     self._result_cache = list(self._iterable_class(self))
celery4geonode   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
celery4geonode   |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
celery4geonode   |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
celery4geonode   |     cursor.execute(sql, params)
celery4geonode   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
celery4geonode   |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
celery4geonode   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
celery4geonode   |     return executor(sql, params, many, context)
celery4geonode   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
celery4geonode   |     return self.cursor.execute(sql, params)
celery4geonode   |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
celery4geonode   |     raise dj_exc_value.with_traceback(traceback) from exc_value
celery4geonode   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
celery4geonode   |     return self.cursor.execute(sql, params)
celery4geonode   | django.db.utils.ProgrammingError: column layers_layer.in_obis does not exist
celery4geonode   | LINE 1: ...r"."outputs", "layers_layer"."obis_pub_interest", "layers_la...
celery4geonode   |                                                              ^
```

**Comment by pieterprovoost** [comment]
@SeritavdW Should be fixed now, please confirm.

**Comment by SeritavdW** [comment]
Fixed! Thank you
